import { exec } from '@actions/exec';
import * as github from '@actions/github';
import { getOctokit } from '@actions/github';

import { logger } from '../lib/logger';

const ACTION_REPO_URL = 'https://github.com/doorloop/ai-docloop';
const ORG_URL = 'https://github.com/doorloop';

function generateBranchName(): string {
	const randomId = Math.random().toString(36).substring(2, 8);
	return `docloop-ai/${randomId}`;
}

function buildPrTitle(): string {
	return '📚 docs: update READMEs via DocLoop AI';
}

function buildPrBody(opts: { sourcePrNumber: number | undefined; sourcePrTitle: string | undefined; baseBranch: string; fileCount: number }): string {
	const { sourcePrNumber, sourcePrTitle, baseBranch, fileCount } = opts;

	const sourceLine =
		sourcePrNumber && sourcePrTitle
			? `Triggered by **#${sourcePrNumber}** ("${sourcePrTitle}") merging into \`${baseBranch}\`.`
			: `Triggered by a merge into \`${baseBranch}\`.`;

	return [
		`## 📚 README updates from DocLoop AI`,
		``,
		`This PR was automatically created by [**DocLoop AI**](${ACTION_REPO_URL}) — [DoorLoop](${ORG_URL})'s open-source GitHub Action that keeps directory READMEs in sync with the codebase using LLMs.`,
		``,
		`### 📦 Source`,
		``,
		sourceLine,
		``,
		`### 📝 What's in this PR`,
		``,
		`${fileCount} README file(s) regenerated based on the changed files in the source PR. Each README is generated from the existing content (when present) plus the diff context, so updates merge in rather than overwriting.`,
		``,
		`### ✅ Reviewing`,
		``,
		`- Skim the diff section by section. The model preserves existing structure when possible.`,
		`- Edit directly on this branch if a section needs adjustment — DocLoop AI will not re-run when this PR merges (the workflow ignores README-only changes).`,
		`- Merge when satisfied.`,
		``,
		`---`,
		``,
		`<sub>🤖 Generated by [DocLoop AI](${ACTION_REPO_URL}) · Maintained by [DoorLoop](${ORG_URL}) · MIT licensed</sub>`,
	].join('\n');
}

interface CommitAndPushOptions {
	readonly baseBranchOverride?: string;
	readonly prTitle?: string;
	readonly requestReviewFromUser?: string;
}

export async function commitAndPush(
	updatedFiles: string[],
	commitMessage: string,
	createPr: boolean,
	context: typeof github.context,
	token: string,
	options?: CommitAndPushOptions,
): Promise<void> {
	if (updatedFiles.length === 0) {
		logger.info('No files to commit');
		return;
	}

	// Resolve base branch: explicit override beats PR context (workflow_dispatch
	// runs without a PR, so the override is the only signal there).
	const baseBranch = options?.baseBranchOverride ?? context.payload.pull_request?.base?.ref;
	if (!baseBranch) {
		throw new Error('Could not determine base branch');
	}

	// Ensure we're on the base branch
	await exec('git', ['checkout', baseBranch]);

	// Configure git user
	await exec('git', ['config', 'user.name', 'github-actions[bot]']);
	await exec('git', ['config', 'user.email', 'github-actions[bot]@users.noreply.github.com']);

	// Stage all updated files. Git uses a single shared index file per repo;
	// running parallel `git add` invocations can corrupt the index or fail
	// with "another git process seems to be running".
	for (const file of updatedFiles) {
		// eslint-disable-next-line no-await-in-loop
		await exec('git', ['add', file]);
	}

	// Check if there are any staged changes
	const exitCode = await exec('git', ['diff', '--cached', '--quiet'], {
		ignoreReturnCode: true,
	});

	// git diff --cached --quiet returns 0 if no changes, non-zero if changes exist
	const hasChanges = exitCode !== 0;

	if (!hasChanges) {
		logger.info('No staged changes to commit');
		return;
	}

	// Commit changes
	await exec('git', ['commit', '-m', commitMessage]);
	logger.info(`Committed ${updatedFiles.length} file(s) with message: ${commitMessage}`);

	// Pull and rebase onto the latest base branch before publishing. The action's
	// runtime can stretch into tens of seconds (OpenAI calls), and another PR may
	// have merged into baseBranch in the meantime. Without this, the generated
	// PR would open on a stale base and show as conflicted on GitHub.
	await exec('git', ['fetch', 'origin', baseBranch]);
	const rebaseExitCode = await exec('git', ['rebase', `origin/${baseBranch}`], {
		ignoreReturnCode: true,
	});
	if (rebaseExitCode !== 0) {
		await exec('git', ['rebase', '--abort'], { ignoreReturnCode: true });
		throw new Error(
			`Failed to rebase generated docs commit onto origin/${baseBranch}. ` +
				`A concurrent change touched the same README file(s). Re-run the workflow to regenerate against the new base.`,
		);
	}

	if (createPr) {
		const branchName = generateBranchName();
		await exec('git', ['checkout', '-b', branchName]);

		await exec('git', ['push', '--set-upstream', 'origin', branchName]);
		logger.info(`Pushed changes to branch: ${branchName}`);

		const octokit = getOctokit(token);
		const sourcePr = context.payload.pull_request;

		const pr = await octokit.rest.pulls.create({
			owner: context.repo.owner,
			repo: context.repo.repo,
			title: options?.prTitle ?? buildPrTitle(),
			head: branchName,
			base: baseBranch,
			body: buildPrBody({
				sourcePrNumber: sourcePr?.number,
				sourcePrTitle: typeof sourcePr?.title === 'string' ? sourcePr.title : undefined,
				baseBranch,
				fileCount: updatedFiles.length,
			}),
		});

		logger.info(`Created PR #${pr.data.number}: ${pr.data.html_url}`);

		if (options?.requestReviewFromUser) {
			try {
				await octokit.rest.pulls.requestReviewers({
					owner: context.repo.owner,
					repo: context.repo.repo,
					pull_number: pr.data.number,
					reviewers: [options.requestReviewFromUser],
				});
				logger.info(`Requested review from @${options.requestReviewFromUser} on PR #${pr.data.number}`);
			} catch (error) {
				const message = error instanceof Error ? error.message : String(error);
				logger.warning(`Could not request review from @${options.requestReviewFromUser} on PR #${pr.data.number}: ${message}`);
			}
		}
	} else {
		// Direct push to the base branch (we're already on it post-rebase).
		await exec('git', ['push', 'origin', baseBranch]);
		logger.info(`Pushed changes directly to ${baseBranch}`);
	}
}
