name: Maintain READMEs

on:
    pull_request:
        types: [closed]

jobs:
    docs:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: doorloop/ai-docloop@v2
              with:
                  openai_api_key: ${{ secrets.OPENAI_API_KEY }}
                  watch: src/features/<FEATURE>/**
                  readme: src/features/<FEATURE>/README.md
